# Generated by Django 4.2.5 on 2024-01-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=150)),
                ('bse_code', models.CharField(max_length=150)),
                ('nse_code', models.CharField(max_length=150)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.industrysector')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cob', models.DateField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.stock')),
            ],
        ),
        migrations.AddField(
            model_name='industrysector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.sector'),
        ),
    ]
