# Generated by Django 4.2.5 on 2024-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_alter_displaystock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
