# Generated by Django 4.2.5 on 2024-01-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_stock_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market_cap',
        ),
        migrations.AddField(
            model_name='displaystock',
            name='market_cap',
            field=models.CharField(default=-2020, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displaystock',
            name='pre_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='displaystock',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.stock'),
        ),
    ]
