# Generated by Django 4.2.5 on 2024-01-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_remove_stock_market_cap_displaystock_market_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaystock',
            name='pre_price',
        ),
    ]
