# Generated by Django 4.2.5 on 2024-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_displaystock_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bse_code',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nse_code',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
