# Generated by Django 4.2.5 on 2024-02-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_alter_displaystock_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
