# Generated by Django 4.2.5 on 2024-02-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_stock_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bse_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.industrysector'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='nse_code',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
